
[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
opacity = 0.9

[general]
live_config_reload = true
import = ["~/.cache/wal/colors-alacritty.toml"]
